### ISSUE TITLE
APK is not installing [INSTALL_FAILED_TEST_ONLY: installPackageLI]

### ISSUE THREAD

**Issue by sushi2k** [51j0/Android-CertKiller#1]
Hi, this is a really nice script! Thanks for creating and sharing. 

I just created an Android App with API >=24 that makes a HTTPs call. I couldn't intercept with Burp, then I used your python script and it worked nicely. The only problem I had was the following 

```bash
➜  Android-CertKiller git:(master) python main.py

Running in default mode:


***************************************
Android CertKiller (v0.1)
***************************************

CertKiller Wizard Mode
---------------------------------
List of devices attached
4200dc72f27bc44d	device

---------------------------------

Enter Application Package Name: nsc.android.mstg.owasp.org.android_nsc

Package: /data/app/nsc.android.mstg.owasp.org.android_nsc-1/base.apk

I. Intitaing APK extraction from device
   complete
------------------------------
I. Decompiling
   complete
------------------------------
I. Applying SSL bypass
   complete
------------------------------
I. Building New APK
   complete
------------------------------
I. Sigining APK
   complete
------------------------------

Would you like to install the APK on your device(y/N): y
------------------------------------
 Installing Unpinned APK
------------------------------
Finished
```

But the app wasn't installed. I found the repackaged APK in the unpinnedapk directory and tried installing it manually but only got an error

```bash
$ adb install base.apk
adb: failed to install base.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
```

I found a workaround for this error 

```
$ adb push base.apk /data/local/tmp
$ adb shell pm install /data/local/tmp/base.apk
Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
$ adb shell pm install -t /data/local/tmp/base.apk
Success
```

Afterwards I was able to intercept the HTTPS request in Burp.

**Comment by 51j0** [comment]
Hi @sushi2k, thank you for highlighting this bug. You were facing the issue because of **android:testonly** flag was set to true in AndroidManifest.xml file 

`android:testOnlyIndicates whether this application is only for testing purposes. For example, it may expose functionality or data outside of itself that would cause a security hole, but is useful for testing. This kind of APK can be installed only through adb and cannot publish it to Google Play.`

However, ill take this up and try to fix it up by March first week.

**Comment by sushi2k** [comment]
Thanks. The script is working really nice and I added it to our OWASP Project the Mobile Security Testing Guide https://github.com/OWASP/owasp-mstg/pull/1141 

Please let me know if you are keen to support us in this project. You can join us in our slack channel https://github.com/OWASP/owasp-mstg#contributions-feature-requests-and-feedback

Cheers,

Sven

**Comment by 51j0** [comment]
Thanks @sushi2k. I would love to contribute to OWASP. will ping you over slack.

**Comment by 51j0** [comment]
I have fixed this bug.
