### ISSUE TITLE
Missing Return Value Check

### ISSUE THREAD

**Issue by shivsahni** [51j0/Android-CertKiller#3]
Whenever a process fails, for example, Apktool may fail during decompilation/building the application, the script fails to check the return value of Apktool and instead shows a successful message.

Please check the return values of each subprocess and notify the user about the cause of failure.

**Comment by 51j0** [comment]
Thank you @shivsahni for pointing this out. I'll try to close this issue by this weekend.

**Comment by 51j0** [comment]
Fixed
